#define USB_VID_BLACKMAGIC_DESIGN	0x1edb
#define USB_PID_BMD_H264_PRO_RECORDER	0xbd43
#define USB_PID_BMD_ATEM_TV_STUDIO	0xbd52

#define CYPRESS_VR_FIRMWARE_LOAD	160
#define VX_CSR_READ			181
#define VX_CSR_WRITE			182
#define VX_CSR_WRITE_MEM_BLOCK		184
#define VX_HOST_READ_REG		185
#define VX_HOST_WRITE_REG		186
#define VX_SYSCONFIG			187
#define VX_MG1264_RESET			188
#define VX_CSR_CFG_READ_MEM_BLOCK	189
#define VX_I2C				191
#define VR_SET_ENDPOINT2_DATA		210
#define VR_EEPROM_READ_BYTE		212
#define VR_IS_FPGA_RUNNING		213
#define VR_READ_REGISTER		214	// used to read IP-address
#define VR_WRITE_REGISTER		215	// used to write IP-address
#define VR_BEGIN_JTAG_PROGRAMMING	219
#define VR_END_JTAG_PROGRAMMING		220
#define VR_EEPROM_WRITE_PAGE		222
#define VR_READY_TO_DOWNLOAD_FIRMWARE	223
#define VR_EEPROM_SECTOR_ERASE		224
#define VR_IS_FPGA_POWERED		225
#define VR_DEBUG			227
#define VR_BEGIN_STAGED_FIRMWARE_UPD	228
#define VR_END_STAGED_FIRMWARE_UPD	229
#define VR_SEND_FPGA_COMMAND		230
#define VR_CLEAR_FPGA_COMMAND		231
#define VR_SEND_DEVICE_STATUS		232
#define VR_START_STREAMING		233
#define VR_SET_INPUT_SOURCE		234
#define VR_SET_IN_TIMECODE		235
#define VR_SET_OUT_TIMECODE		236
#define VR_SEND_SERIAL_PORT_COMMAND	237
#define VR_GET_FIFO_LEVEL		238
#define VR_FUJITSU_READ			239
#define VR_FUJITSU_WRITE		240
#define VR_FUJITSU_START_ENCODING	241
#define VR_FUJITSU_STOP_ENCODING	242
#define VR_GET_SERIAL_LOOPBACK		243
#define VR_GET_SERIAL_DEVICE_ID		244
#define VR_SET_AUDIO_DELAY		245

enum FX2_H264_PROFILE {
	FX2_H264_HIGH = 1,
	FX2_H264_MAIN,
	FX2_H264_BASELINE,
};
